# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
os:
  - linux
  # - osx  # we don't do any binary dependencies or OS specific magic
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - echo "cacert=/etc/ssl/certs/ca-certificates.crt" > ~/.curlrc
    - julia -e 'Pkg.clone("https://github.com/dcjones/YAML.jl.git","YAML"); Pkg.checkout("YAML","tags")'
    - julia -e 'Pkg.clone("https://github.com/EconForge/Dolang.git")'
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Dolo"); Pkg.test("Dolo"; coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - echo $TRAVIS_OS_NAME
    - if [ $TRAVIS_JULIA_VERSION = "release" ] && [ $TRAVIS_OS_NAME = "linux" ]; then
         julia -e 'cd(Pkg.dir("Dolo")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder());';
      fi
